apiVersion: v2
name: my-stack
version: 0.1.0
dependencies:
  - name: api
    version: 0.1.*
    repository: "file://charts/api"
  - name: postgresql
    version: 16.*
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: redis
    version: 19.*
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: neo4j
    version: 5.*
    repository: "oci://registry-1.docker.io/bitnamicharts"

