services:
  db:
    image: postgres:16-alpine
    container_name: deliverydrive-db
    restart: unless-stopped
    environment:
      POSTGRES_USER       : deliverydrive
      POSTGRES_PASSWORD   : deliverydrive
      POSTGRES_DB         : deliverydrive
      TZ                  : Europe/Moscow
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - archive_mode=on
      - -c
      - archive_command=cp %p /var/lib/postgresql/data/pg_wal/%f
      - -c
      - wal_level=replica
    volumes:
      - db_data:/var/lib/postgresql/data

  orm-service:
    build:
      context: ./app/orm-service
    image: deliverydrive/orm-service:latest
    container_name: orm-service
    depends_on: [db]
    restart: unless-stopped
    environment:
      POSTGRES_USER       : deliverydrive
      POSTGRES_PASSWORD   : deliverydrive
      POSTGRES_HOST       : db
      POSTGRES_PORT       : 5432
      POSTGRES_DB         : deliverydrive
      TZ                  : Europe/Moscow
      JWT_SECRET          : "change-this-in-prod"
      JWT_ALG             : "HS256"
      ACCESS_TOKEN_TTL_MIN: 43200  # 30 дней
    volumes:
      - ./app/orm-service/static:/app/static
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"

  auth-service:
    build:
      context: ./app/auth-service
    image: deliverydrive/auth-service:latest
    container_name: auth-service
    depends_on: [db]
    restart: unless-stopped
    environment:
      POSTGRES_USER       : deliverydrive
      POSTGRES_PASSWORD   : deliverydrive
      POSTGRES_HOST       : db
      POSTGRES_PORT       : 5432
      POSTGRES_DB         : deliverydrive
      TZ                  : Europe/Moscow
      JWT_SECRET          : "change-this-in-prod"
      JWT_ALG             : "HS256"
      ACCESS_TOKEN_TTL_MIN: 43200  # 30 дней
    command: uvicorn src.main:app --host 0.0.0.0 --port 9000
    ports:
      - "9090:9000"

  seed-db:
    image: deliverydrive/orm-service:latest
    depends_on: [db]
    environment:
      POSTGRES_USER       : deliverydrive
      POSTGRES_PASSWORD   : deliverydrive
      POSTGRES_HOST       : db
      POSTGRES_PORT       : 5432
      POSTGRES_DB         : deliverydrive
    command: python -m src.db.init_db
    restart: "no"

  # backup-service:
  #   build:
  #     context: ./app/backup-service
  #   image: deliverydrive/backup-service:latest
  #   container_name: backup-service
  #   depends_on: [db]
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: deliverydrive
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB: deliverydrive
  #     PGPASSWORD: deliverydrive
  #   volumes:
  #     - db_data:/var/lib/postgresql/data:ro
  #     - ./backups:/backups

volumes:
  db_data:
