image:
  repository: docker.io/miomelliot/orm-server
  tag: "latest"

service:
  port: 8000

volumeMounts:
  - name: avatars
    mountPath: /data/avatars

volumes:
  - name: avatars
    persistentVolumeClaim:
      claimName: avatars-pvc

env:
  - name: POSTGRES_DB
    value: mydb
  - name: POSTGRES_USER
    value: myuser
  - name: POSTGRES_PASSWORD
    value: mypassword
  - name: POSTGRES_HOST
    value: postgres-service
  - name: POSTGRES_PORT
    value: "5432"
