pg:
  auth:
    username: mio
    password: super-secret
    database: mydb
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
grafana:
  adminPassword: "dont-put-me-in-git"
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki:3100
loki:
  loki:
    deploymentMode: SingleBinary
    scalable: false
    backend:
      enabled: false
    read:
      enabled: false
    write:
      enabled: false
    auth_enabled: false
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ""

    storage:
      type: filesystem
      bucketNames:
        chunks: dummy
        ruler: dummy
        admin: dummy

    storage_config:
      filesystem:
        directory: /var/loki/chunks

    schemaConfig:
      configs:
        - from: "2025-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

alloy:
  config:
    metrics:
      wal_directory: /var/lib/alloy/wal
